#!/bin/sh

SCRIPT=/home/xtreamcodes
USER=$(whoami)

if [ $USER != "root" ]]; then
  echo "Please run as root!"
  exit 0
fi

start() {
  pids=$(pgrep -u xtreamcodes nginx | wc -l)
  if [ $pids != 0 ]; then
    echo 'XtreamCodes is already running'
    return 1
  fi
  echo 'Starting XtreamCodes...'
  sudo chown -R xtreamcodes:xtreamcodes /sys/class/net
  sudo chown -R xtreamcodes:xtreamcodes /home/xtreamcodes
  sudo -u xtreamcodes $SCRIPT/bin/nginx/sbin/nginx >/dev/null 2>/dev/null
  sudo -u xtreamcodes $SCRIPT/bin/nginx_rtmp/sbin/nginx_rtmp >/dev/null 2>/dev/null
  /sbin/start-stop-daemon --start --quiet --pidfile /home/xtreamcodes/php/VaiIb8.pid --exec /home/xtreamcodes/php/sbin/php-fpm -- --daemonize --fpm-config /home/xtreamcodes/php/etc/VaiIb8.conf
  /sbin/start-stop-daemon --start --quiet --pidfile /home/xtreamcodes/php/JdlJXm.pid --exec /home/xtreamcodes/php/sbin/php-fpm -- --daemonize --fpm-config /home/xtreamcodes/php/etc/JdlJXm.conf
  /sbin/start-stop-daemon --start --quiet --pidfile /home/xtreamcodes/php/CWcfSP.pid --exec /home/xtreamcodes/php/sbin/php-fpm -- --daemonize --fpm-config /home/xtreamcodes/php/etc/CWcfSP.conf

  sudo -u xtreamcodes /home/xtreamcodes/php/bin/php /home/xtreamcodes/crons/setup_cache.php
  sudo -u xtreamcodes /home/xtreamcodes/php/bin/php /home/xtreamcodes/tools/signals.php >/dev/null 2>/dev/null &
  echo 'Running in foreground...'
  sleep infinity
}

stop() {
  pids=$(pgrep -u xtreamcodes nginx | wc -l)
  if [ $pids = 0 ]; then
    echo 'XtreamCodes is not running'
    return 1
  fi
  echo 'Stopping XtreamCodes...'
  sudo killall -u xtreamcodes
  sleep 1
  sudo killall -u xtreamcodes
  sleep 1
  sudo killall -u xtreamcodes
}

restart() {
  ps -U xtreamcodes | egrep -v "ffmpeg|PID" | awk '{print $1}' | xargs kill -9
  start
}

reload() {
  pids=$(pgrep -u xtreamcodes nginx | wc -l)
  if [ $pids = 0 ]]; then
    echo 'XtreamCodes is not running'
    return 1
  fi
  echo 'Reloading XtreamCodes...'
  sudo -u xtreamcodes $SCRIPT/nginx/sbin/nginx -s reload
  sudo -u xtreamcodes $SCRIPT/nginx_rtmp/sbin/nginx_rtmp -s reload
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload)
    reload
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
esac

exit 0
